v0.4.1: - Improvement: moved some functions from PencilDrawing to PencilStroke - Commit will be rejected if a test fails

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,4 +11,12 @@ jobs:
     - run: flutter --version
     - run: dart analyze
     - run: mkdir test/resulting_output
-    - run: flutter test
+    - run: flutter test --machine > test_results.json
+
+    - name: Check Test Results
+        id: check-test-results
+        run: |
+          if [ "$(grep -c 'All tests passed!' $GITHUB_WORKSPACE/test-results.json)" -ne 1 ]; then
+            echo "One or more tests failed. Please fix the failing tests and try again."
+            exit 1
+          fi
