Fix for action file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,10 +12,8 @@ jobs:
     - run: dart analyze
     - run: mkdir test/resulting_output
     - run: flutter test --machine > test_results.json
-
-    - name: Check Test Results
-        run: |
-          if [ "$(grep -c 'All tests passed!' $GITHUB_WORKSPACE/test-results.json)" -ne 1 ]; then
-            echo "One or more tests failed. Please fix the failing tests and try again."
-            exit 1
-          fi
+    - run: |
+        if [ "$(grep -c 'All tests passed!' $GITHUB_WORKSPACE/test-results.json)" -ne 1 ]; then
+          echo "One or more tests failed. Please fix the failing tests and try again."
+          exit 1
+        fi
